name: build
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os-name }}
    strategy:
      matrix:
        os-name: [ ubuntu-latest, windows-2022, macos-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x.x
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: install dependencies (ubuntu)
        if: ${{ matrix.os-name == 'ubuntu-latest' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-common-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev cmake
      - name: install dependencies (macos)
        if: ${{ matrix.os-name == 'macos-latest' }}
        shell: bash
        run: |
          brew install cmake
      - name: build
        shell: bash
        run: |
          dotnet restore scriptcore/scriptcore.csproj
          cmake --preset default
          cmake --build --preset default